services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=984
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /docker/plex:/config
      - /docker/media:/media:shared
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - /docker/sonarr:/config
      - /docker/media:/media:shared #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - /docker/prowlarr:/config
      - /docker/prowlarr/Custom:/config/Definitions/Custom
    ports:
      - 9696:9696
    restart: unless-stopped
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - /docker/radarr:/config
      - /docker/media:/media:shared
    ports:
      - 7878:7878
    restart: unless-stopped
  decypharr:
    image: cy01/blackhole:latest
    container_name: decypharr
    ports:
      - "8282:8282"
    environment:
      - PUID=1001
      - PGID=984
    volumes:
      - ./configs/:/app # config.json must be in this directory
      - /docker/media/:/media:rshared
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1001
      - PGID=984
      - TZ=Etc/UTC
    volumes:
      - /docker/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
